/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import bean.Articulo;
import bean.AuditoriaSistema;
import bean.Proveedor;
import java.awt.EventQueue;
import java.beans.Beans;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author tammy
 */
public class ArticuloCreate extends javax.swing.JFrame {
    private char ch;
    private int resp;
  private int id;
 
  
    public ArticuloCreate() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("proyectoPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT a FROM Articulo a");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        proveedorRenderizar1 = new renderizar.ProveedorRenderizar();
        proveedorQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Proveedor p");
        proveedorList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : proveedorQuery.getResultList();
        jPanel3 = new javax.swing.JPanel();
        lbl_registrarC = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_nombre = new javax.swing.JLabel();
        cantidadStockLabel = new javax.swing.JLabel();
        cantidadMinimaLabel = new javax.swing.JLabel();
        codigoProveedorLabel = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_cantidadStock = new javax.swing.JTextField();
        tf_cantidadMinima = new javax.swing.JTextField();
        combo_proveedor = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        btn_cancelar3 = new javax.swing.JButton();
        btn_guardar3 = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        proveedorRenderizar1.setText("proveedorRenderizar1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lbl_registrarC.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        lbl_registrarC.setForeground(new java.awt.Color(255, 255, 255));
        lbl_registrarC.setText("Crear Articulo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_registrarC)
                .addGap(163, 163, 163))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_registrarC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_nombre.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lbl_nombre.setText("Nombre:");

        cantidadStockLabel.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        cantidadStockLabel.setText("Cantidad Stock:");

        cantidadMinimaLabel.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        cantidadMinimaLabel.setText("Cantidad Minima:");

        codigoProveedorLabel.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        codigoProveedorLabel.setText("Codigo Proveedor:");

        tf_cantidadStock.setEnabled(false);

        combo_proveedor.setRenderer(proveedorRenderizar1);

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, proveedorList, combo_proveedor);
        bindingGroup.addBinding(jComboBoxBinding);

        combo_proveedor.addActionListener(formListener);
        combo_proveedor.addFocusListener(formListener);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tf_cantidadStock, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(codigoProveedorLabel)
                            .addGap(60, 60, 60)))
                    .addComponent(cantidadStockLabel)
                    .addComponent(lbl_nombre)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cantidadMinimaLabel)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_cantidadMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadStockLabel)
                    .addComponent(tf_cantidadStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadMinimaLabel)
                    .addComponent(tf_cantidadMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigoProveedorLabel)
                    .addComponent(combo_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_cancelar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        btn_cancelar3.setText("Cancelar");
        btn_cancelar3.addActionListener(formListener);

        btn_guardar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btn_guardar3.setText("Guardar");
        btn_guardar3.addActionListener(formListener);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btn_guardar3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btn_cancelar3)
                .addGap(34, 34, 34))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btn_cancelar3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_guardar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 182, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.FocusListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == combo_proveedor) {
                ArticuloCreate.this.combo_proveedorActionPerformed(evt);
            }
            else if (evt.getSource() == btn_cancelar3) {
                ArticuloCreate.this.btn_cancelar3ActionPerformed(evt);
            }
            else if (evt.getSource() == btn_guardar3) {
                ArticuloCreate.this.btn_guardar3ActionPerformed(evt);
            }
        }

        public void focusGained(java.awt.event.FocusEvent evt) {
        }

        public void focusLost(java.awt.event.FocusEvent evt) {
            if (evt.getSource() == combo_proveedor) {
                ArticuloCreate.this.combo_proveedorFocusLost(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelar3ActionPerformed

    private void btn_guardar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar3ActionPerformed
        // TODO add your handling code here:
        //int min= Integer.parseInt(null)
       if (((Integer.parseInt(tf_cantidadMinima.getText()))<0)&& ((Integer.parseInt(tf_cantidadStock.getText()))<0)){
           JOptionPane.showMessageDialog(null,"No se permiten campos con valores negativos", "Error",JOptionPane.ERROR_MESSAGE);
            return;
       }
     
        if(tf_nombre.getText().length()==0 || tf_cantidadMinima.getText().length()==0
           /* || tf_cantidadStock.getText().length()==0 */|| combo_proveedor.getSelectedIndex()<-1)
            {
            JOptionPane.showMessageDialog(null,"No se permiten campos con valores nulos", "Error",JOptionPane.ERROR_MESSAGE);
            return;
            }
        else {
                //verificar que no se ingrese nombre repetido
               query=entityManager.createNamedQuery("Articulo.findByNombre");
               query.setParameter("nombre", tf_nombre.getText().toLowerCase());
               List<Articulo> art=query.getResultList();
               if(art.size()!=0){
                   JOptionPane.showMessageDialog(null,"El nombre del articulo ya ha sido registrado", "Error",JOptionPane.ERROR_MESSAGE);
                   tf_nombre.setText(null);
                   return;
               }
               resp=  JOptionPane.showConfirmDialog(null,"Desea Registrar una nuevo articulo?", "Confirmar Creación",JOptionPane.YES_NO_OPTION );
               if (resp==JOptionPane.YES_OPTION){
                   Articulo a=new Articulo();
                  tf_cantidadStock.setText("0");
                   a.setNombre(tf_nombre.getText().toLowerCase());
                   //a.setCantidadMinima();
                   a.setCantidadMinima(Integer.parseInt(tf_cantidadMinima.getText()));
                   a.setCantidadStock(Integer.parseInt(tf_cantidadStock.getText()));
                   Proveedor p=(Proveedor) combo_proveedor.getSelectedItem();
                   a.setCodigoProveedor(p);
                   entityManager.getTransaction().begin();
                   entityManager.persist(a);
                   entityManager.flush();
                   //registramos los datos de la auditoria
                    AuditoriaSistema as=new AuditoriaSistema();
                    as.setAccion("Creación");
                    as.setTabla("Articulo");
                    as.setAntes(a.toString());
                    as.setDespues("No hay cambios");
                    //trabajamos con la fecha
                    Date fecha=new Date();
                    DateFormat formato=new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
                    as.setFechaHora((formato.format(fecha)));
                    as.setUsuario("nadie");
                    entityManager.persist(as);
                    entityManager.getTransaction().commit();
                    entityManager.close();
                    JOptionPane.showMessageDialog(null,"Creación exitosa", "Confirmación",JOptionPane.INFORMATION_MESSAGE);
               }
        }
        this.dispose();   
        
            
       /* }else{
            resp=  JOptionPane.showConfirmDialog(null,"Desea Registrar un nuevo Articulo?", "Confirmar Creación",JOptionPane.YES_NO_OPTION );
            if (resp==JOptionPane.YES_OPTION){
              //  entityManager.getTransaction().begin();
                Articulo a=new Articulo();
                a.setNombre(tf_nombre.getText());
                a.setCantidadStock(Integer.parseInt(tf_cantidadStock.getText()));
                a.setCantidadMinima(Integer.parseInt(tf_cantidadMinima.getText()));
                Proveedor p=(Proveedor) combo_proveedor.getSelectedItem();
                a.setCodigoProveedor(p);
                entityManager.getTransaction().begin();
                entityManager.persist(a);
                entityManager.flush();

                //registramos los datos necesarios para la auditoria
                AuditoriaSistema as=new AuditoriaSistema();
                as.setAccion("Inserción");
                as.setTabla("Articulo");
                as.setAntes(a.toString());
                as.setDespues("No hay cambios");
                //trabajamos con la fecha
                Date fecha=new Date();
                DateFormat formato=new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
                as.setFechaHora(formato.format(fecha));
                as.setUsuario(LoginView.nombreUsuario);
                entityManager.persist(as);
                entityManager.getTransaction().commit();
                entityManager.close();
                JOptionPane.showMessageDialog(null,"Creación exitosa", "Confirmación",JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            }else{
                this.setVisible(false);
            }
        }*/
    }//GEN-LAST:event_btn_guardar3ActionPerformed

    private void combo_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_proveedorActionPerformed

    private void combo_proveedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combo_proveedorFocusLost
        // TODO add your handling code here:
        //    ProductoServicio p=(ProductoServicio) list_ps.getSelectedItem();
        //  tf_precio.setText(Integer.toString(p.getCosto()));
        //Proveedor pc = (Proveedor) combo_proveedor.getSelectedItem();

    }//GEN-LAST:event_combo_proveedorFocusLost

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar3;
    private javax.swing.JButton btn_guardar3;
    private javax.swing.JLabel cantidadMinimaLabel;
    private javax.swing.JLabel cantidadStockLabel;
    private javax.swing.JLabel codigoProveedorLabel;
    private javax.swing.JComboBox combo_proveedor;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_registrarC;
    private java.util.List<bean.Articulo> list;
    private java.util.List<bean.Proveedor> proveedorList;
    private javax.persistence.Query proveedorQuery;
    private renderizar.ProveedorRenderizar proveedorRenderizar1;
    private javax.persistence.Query query;
    private javax.swing.JTextField tf_cantidadMinima;
    private javax.swing.JTextField tf_cantidadStock;
    public javax.swing.JTextField tf_nombre;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArticuloCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArticuloCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArticuloCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArticuloCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame=new ArticuloCreate();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
                frame.setTitle("Registrar Articulo");
                
            }
        });
    }
    
}
