/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuAdminSist.java
 *
 * Created on 14/07/2015, 03:36:05 PM
 */

package view;

import bean.AuditoriaSistema;
import bean.Rol;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JFrame;
import static view.RolEliminar.tf_identi;

/**
 *
 * @author Jorge
 */
public class MenuEncargadoDeposito extends javax.swing.JFrame {
    public static int opcion=0;

    /** Creates new form MenuAdminSist */
    public MenuEncargadoDeposito() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_factura = new javax.swing.JMenu();
        mItem_crearF = new javax.swing.JMenuItem();
        mItem_editarF = new javax.swing.JMenuItem();
        mItem_eliminarF = new javax.swing.JMenuItem();
        mItem_buscarF = new javax.swing.JMenuItem();
        menu_articulo = new javax.swing.JMenu();
        mitem_crearArt = new javax.swing.JMenuItem();
        mitem_editarArt = new javax.swing.JMenuItem();
        mitem_eliminarArt = new javax.swing.JMenuItem();
        miItem_buscarArticulo = new javax.swing.JMenuItem();
        menu_ordenCompra = new javax.swing.JMenu();
        menu_registrarOC = new javax.swing.JMenuItem();
        menu_modifOC = new javax.swing.JMenuItem();
        menu_eliminarOC = new javax.swing.JMenuItem();
        menu_visualizarOC = new javax.swing.JMenuItem();
        menu_salir = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu Administrador del Sistema");

        jMenuBar1.setBackground(new java.awt.Color(211, 219, 227));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        menu_factura.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_factura.setText("Administrar Factura de Compras");
        menu_factura.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        menu_factura.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        mItem_crearF.setText("Registrar Factura Compra");
        mItem_crearF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_crearFActionPerformed(evt);
            }
        });
        menu_factura.add(mItem_crearF);

        mItem_editarF.setText("Modificar Factura Compra");
        mItem_editarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_editarFActionPerformed(evt);
            }
        });
        menu_factura.add(mItem_editarF);

        mItem_eliminarF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trash.png"))); // NOI18N
        mItem_eliminarF.setText("Eliminar Factura Compra");
        mItem_eliminarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_eliminarFActionPerformed(evt);
            }
        });
        menu_factura.add(mItem_eliminarF);

        mItem_buscarF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom.png"))); // NOI18N
        mItem_buscarF.setText("Buscar Factura Compra");
        mItem_buscarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_buscarFActionPerformed(evt);
            }
        });
        menu_factura.add(mItem_buscarF);

        jMenuBar1.add(menu_factura);

        menu_articulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_articulo.setText("Administrar Articulos");

        mitem_crearArt.setText("Crear Articulo");
        mitem_crearArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_crearArtActionPerformed(evt);
            }
        });
        menu_articulo.add(mitem_crearArt);

        mitem_editarArt.setText("Modificar Articulo");
        mitem_editarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_editarArtActionPerformed(evt);
            }
        });
        menu_articulo.add(mitem_editarArt);

        mitem_eliminarArt.setText("Eliminar Articulo");
        mitem_eliminarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_eliminarArtActionPerformed(evt);
            }
        });
        menu_articulo.add(mitem_eliminarArt);

        miItem_buscarArticulo.setText("Buscar Articulo");
        miItem_buscarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miItem_buscarArticuloActionPerformed(evt);
            }
        });
        menu_articulo.add(miItem_buscarArticulo);

        jMenuBar1.add(menu_articulo);

        menu_ordenCompra.setText("Administrar Ordenes de Compra");

        menu_registrarOC.setText("Registrar Orden Compra");
        menu_registrarOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_registrarOCActionPerformed(evt);
            }
        });
        menu_ordenCompra.add(menu_registrarOC);

        menu_modifOC.setText("Modificar Orden Compra");
        menu_ordenCompra.add(menu_modifOC);

        menu_eliminarOC.setText("Eliminar Orden Compra");
        menu_ordenCompra.add(menu_eliminarOC);

        menu_visualizarOC.setText("Visualizar Orden Compras");
        menu_ordenCompra.add(menu_visualizarOC);

        jMenuBar1.add(menu_ordenCompra);

        menu_salir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_salir.setText("Salir");
        menu_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_salirMouseClicked(evt);
            }
        });
        menu_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_salirActionPerformed(evt);
            }
        });
        jMenuBar1.add(menu_salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mItem_buscarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_buscarFActionPerformed
      
    }//GEN-LAST:event_mItem_buscarFActionPerformed

    private void mItem_eliminarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_eliminarFActionPerformed
      
    }//GEN-LAST:event_mItem_eliminarFActionPerformed

    private void mItem_editarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_editarFActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_mItem_editarFActionPerformed

    private void menu_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_salirMouseClicked

            // TODO add your handling code here:
            EntityManagerFactory fact=Persistence.createEntityManagerFactory("proyectoPU");
            EntityManager ema= fact.createEntityManager();
            ema.getTransaction().begin();
            //registramos los datos necesarios para la auditoria
            AuditoriaSistema as=new AuditoriaSistema();
            as.setAccion("Cerro Sesion");
            as.setTabla("Ninguna");
            //trabajamos con la fecha
            Date fecha=new Date();
            DateFormat formato=new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
            as.setFechaHora(formato.format(fecha));
            as.setUsuario(LoginView.nombreUsuario);
            ema.persist(as);
            ema.getTransaction().commit();
            ema.close();
            this.setVisible(false);
            String args[]=new String[1];
            args[0]="Ingreso al sistema";
            LoginView.main(args);
    }//GEN-LAST:event_menu_salirMouseClicked

    private void mitem_crearArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_crearArtActionPerformed
        // TODO add your handling code here:
        String args[]=new String[1];
        args[0]="Crear Articulo";
        ArticuloCreate.main(args);
    }//GEN-LAST:event_mitem_crearArtActionPerformed

    private void miItem_buscarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miItem_buscarArticuloActionPerformed
        // TODO add your handling code here:
      opcion = 3;
       String args[]=new String[1];
        args[0]="Buscar Articulo";
        ArticuloBuscar.main(args);
      
    }//GEN-LAST:event_miItem_buscarArticuloActionPerformed

    private void mitem_editarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_editarArtActionPerformed

       // TODO add your handling code here:
        opcion = 1;
        String args[]=new String[1];
        args[0]="Buscar Articulo";
        ArticuloBuscar.main(args);
      
    }//GEN-LAST:event_mitem_editarArtActionPerformed

    private void mitem_eliminarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_eliminarArtActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        opcion = 2;
       String args[]=new String[1];
        args[0]="Buscar Articulo";
        ArticuloBuscar.main(args);
      
    }//GEN-LAST:event_mitem_eliminarArtActionPerformed

    private void menu_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_salirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_salirActionPerformed

    private void mItem_crearFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_crearFActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_mItem_crearFActionPerformed

    private void menu_registrarOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_registrarOCActionPerformed
        // TODO add your handling code here:
        opcion  = 1;
          String args[]=new String[1];
        args[0]="Registrar Orden de Compra";
       ProveedorBuscar.main(args);
    }//GEN-LAST:event_menu_registrarOCActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(final String args[]) {
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame=new MenuEncargadoDeposito();
                frame.setTitle("Menu Encargado");
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem mItem_buscarF;
    private javax.swing.JMenuItem mItem_crearF;
    private javax.swing.JMenuItem mItem_editarF;
    private javax.swing.JMenuItem mItem_eliminarF;
    private javax.swing.JMenu menu_articulo;
    private javax.swing.JMenuItem menu_eliminarOC;
    private javax.swing.JMenu menu_factura;
    private javax.swing.JMenuItem menu_modifOC;
    private javax.swing.JMenu menu_ordenCompra;
    private javax.swing.JMenuItem menu_registrarOC;
    private javax.swing.JMenu menu_salir;
    private javax.swing.JMenuItem menu_visualizarOC;
    private javax.swing.JMenuItem miItem_buscarArticulo;
    private javax.swing.JMenuItem mitem_crearArt;
    private javax.swing.JMenuItem mitem_editarArt;
    private javax.swing.JMenuItem mitem_eliminarArt;
    // End of variables declaration//GEN-END:variables

}
