/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import javax.swing.JFrame;

/**
 *
 * @author Jorge
 */
public class MenuAdminHotel extends javax.swing.JFrame {
    public static int opcion=0;

    /**
     * Creates new form MenuAdminHotel
     */
    public MenuAdminHotel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mItem_buscarCH = new javax.swing.JMenu();
        mItem_crearCH = new javax.swing.JMenuItem();
        mItem_editarCH = new javax.swing.JMenuItem();
        mItem_eliminarCH = new javax.swing.JMenuItem();
        mItem_buscar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mItem_buscarCH.setText("Administrar Categoría de Habitación");

        mItem_crearCH.setText("Crear Categoría");
        mItem_crearCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_crearCHActionPerformed(evt);
            }
        });
        mItem_buscarCH.add(mItem_crearCH);

        mItem_editarCH.setText("Editar Categoría");
        mItem_editarCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_editarCHActionPerformed(evt);
            }
        });
        mItem_buscarCH.add(mItem_editarCH);

        mItem_eliminarCH.setText("Eliminar Categoría");
        mItem_eliminarCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_eliminarCHActionPerformed(evt);
            }
        });
        mItem_buscarCH.add(mItem_eliminarCH);

        mItem_buscar.setText("Buscar Categoría");
        mItem_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_buscarActionPerformed(evt);
            }
        });
        mItem_buscarCH.add(mItem_buscar);

        jMenuBar1.add(mItem_buscarCH);

        jMenu2.setText("Salir");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mItem_crearCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_crearCHActionPerformed
        // TODO add your handling code here:
        String args[]=new String[1];
        args[0]="Crear Categoría de Habitación";
        CategHabitCreate.main(args);
    }//GEN-LAST:event_mItem_crearCHActionPerformed

    private void mItem_editarCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_editarCHActionPerformed
        // TODO add your handling code here:
        opcion=1;
        String args[]=new String[1];
        args[0]="Buscar Categoría de Habitación";
        CategHabitBuscar.main(args); 
    }//GEN-LAST:event_mItem_editarCHActionPerformed

    private void mItem_eliminarCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_eliminarCHActionPerformed
        // TODO add your handling code here:
        opcion=2;
        String args[]=new String[1];
        args[0]="Buscar Categoría de Habitación";
        CategHabitBuscar.main(args);
    }//GEN-LAST:event_mItem_eliminarCHActionPerformed

    private void mItem_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_buscarActionPerformed
        // TODO add your handling code here:
        opcion=3;
        String args[]=new String[1];
        args[0]="Buscar Categoría de Habitación";
        CategHabitBuscar.main(args);
    }//GEN-LAST:event_mItem_buscarActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdminHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdminHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdminHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdminHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame=new MenuAdminHotel();
                frame.setTitle("Menu Administrador del Hotel");
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mItem_buscar;
    private javax.swing.JMenu mItem_buscarCH;
    private javax.swing.JMenuItem mItem_crearCH;
    private javax.swing.JMenuItem mItem_editarCH;
    private javax.swing.JMenuItem mItem_eliminarCH;
    // End of variables declaration//GEN-END:variables
}
