/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import javax.swing.JFrame;

/**
 *
 * @author Jorge
 */
public class MenuAdminHotel extends javax.swing.JFrame {
    public static int opcion=0;

    /**
     * Creates new form MenuAdminHotel
     */
    public MenuAdminHotel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menu_categHabitacion = new javax.swing.JMenu();
        mItem_crearCH = new javax.swing.JMenuItem();
        mItem_editarCH = new javax.swing.JMenuItem();
        mItem_eliminarCH = new javax.swing.JMenuItem();
        mItem_buscar = new javax.swing.JMenuItem();
        menu_Habitacion = new javax.swing.JMenu();
        mItem_crearHabit = new javax.swing.JMenuItem();
        mItem_editarHabit = new javax.swing.JMenuItem();
        mItem_eliminarHabit = new javax.swing.JMenuItem();
        mItem_buscarHabit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        menu_categHabitacion.setText("Administrar Categoría de Habitación");

        mItem_crearCH.setText("Crear Categoría");
        mItem_crearCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_crearCHActionPerformed(evt);
            }
        });
        menu_categHabitacion.add(mItem_crearCH);

        mItem_editarCH.setText("Editar Categoría");
        mItem_editarCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_editarCHActionPerformed(evt);
            }
        });
        menu_categHabitacion.add(mItem_editarCH);

        mItem_eliminarCH.setText("Eliminar Categoría");
        mItem_eliminarCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_eliminarCHActionPerformed(evt);
            }
        });
        menu_categHabitacion.add(mItem_eliminarCH);

        mItem_buscar.setText("Buscar Categoría");
        mItem_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_buscarActionPerformed(evt);
            }
        });
        menu_categHabitacion.add(mItem_buscar);

        jMenuBar1.add(menu_categHabitacion);

        menu_Habitacion.setText("Administrar Habitación");
        menu_Habitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_HabitacionActionPerformed(evt);
            }
        });

        mItem_crearHabit.setText("Crear Habitación");
        mItem_crearHabit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_crearHabitActionPerformed(evt);
            }
        });
        menu_Habitacion.add(mItem_crearHabit);

        mItem_editarHabit.setText("Editar Habitación");
        mItem_editarHabit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_editarHabitActionPerformed(evt);
            }
        });
        menu_Habitacion.add(mItem_editarHabit);

        mItem_eliminarHabit.setText("Eliminar Habitación");
        mItem_eliminarHabit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_eliminarHabitActionPerformed(evt);
            }
        });
        menu_Habitacion.add(mItem_eliminarHabit);

        mItem_buscarHabit.setText("Buscar Habitación");
        mItem_buscarHabit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItem_buscarHabitActionPerformed(evt);
            }
        });
        menu_Habitacion.add(mItem_buscarHabit);

        jMenuBar1.add(menu_Habitacion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mItem_crearCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_crearCHActionPerformed
        // TODO add your handling code here:
        String args[]=new String[1];
        args[0]="Crear Categoría de Habitación";
        CategHabitCreate.main(args);
    }//GEN-LAST:event_mItem_crearCHActionPerformed

    private void mItem_editarCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_editarCHActionPerformed
        // TODO add your handling code here:
        opcion=1;
        String args[]=new String[1];
        args[0]="Buscar Categoría de Habitación";
        CategHabitBuscar.main(args); 
    }//GEN-LAST:event_mItem_editarCHActionPerformed

    private void mItem_eliminarCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_eliminarCHActionPerformed
        // TODO add your handling code here:
        opcion=2;
        String args[]=new String[1];
        args[0]="Buscar Categoría de Habitación";
        CategHabitBuscar.main(args);
    }//GEN-LAST:event_mItem_eliminarCHActionPerformed

    private void mItem_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_buscarActionPerformed
        // TODO add your handling code here:
        opcion=3;
        String args[]=new String[1];
        args[0]="Buscar Categoría de Habitación";
        CategHabitBuscar.main(args);
    }//GEN-LAST:event_mItem_buscarActionPerformed

    private void menu_HabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_HabitacionActionPerformed
     
    }//GEN-LAST:event_menu_HabitacionActionPerformed

    private void mItem_buscarHabitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_buscarHabitActionPerformed
        // TODO add your handling code here:
        opcion=3;
        String args[]=new String[1];
        args[0]="Buscar Habitación";
        HabitacionBuscar.main(args);
    }//GEN-LAST:event_mItem_buscarHabitActionPerformed

    private void mItem_crearHabitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_crearHabitActionPerformed
        // TODO add your handling code here:
       
        String args[]=new String[1];
        args[0]="Crear Habitación";
        HabitacionCreate.main(args);
    }//GEN-LAST:event_mItem_crearHabitActionPerformed

    private void mItem_editarHabitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_editarHabitActionPerformed
        // TODO add your handling code here:
        opcion=1;
        String args[]=new String[1];
        args[0]="Buscar Habitación";
        HabitacionBuscar.main(args);
    }//GEN-LAST:event_mItem_editarHabitActionPerformed

    private void mItem_eliminarHabitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItem_eliminarHabitActionPerformed
        // TODO add your handling code here:
         opcion=2;
        String args[]=new String[1];
        args[0]="Buscar Habitación";
        HabitacionBuscar.main(args);
                                     
    }//GEN-LAST:event_mItem_eliminarHabitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdminHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdminHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdminHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdminHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame=new MenuAdminHotel();
                frame.setTitle("Menu Administrador del Hotel");
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mItem_buscar;
    private javax.swing.JMenuItem mItem_buscarHabit;
    private javax.swing.JMenuItem mItem_crearCH;
    private javax.swing.JMenuItem mItem_crearHabit;
    private javax.swing.JMenuItem mItem_editarCH;
    private javax.swing.JMenuItem mItem_editarHabit;
    private javax.swing.JMenuItem mItem_eliminarCH;
    private javax.swing.JMenuItem mItem_eliminarHabit;
    private javax.swing.JMenu menu_Habitacion;
    private javax.swing.JMenu menu_categHabitacion;
    // End of variables declaration//GEN-END:variables
}
